language: python
python:
  - "3.6"
install:
  - pip install -r requirements_travis.txt
script:
  - pytest tests/test_quest.py

dist:
  trusty

addons:
  sonarcloud:
    organization: szymonmichalski
    token:
      secure: 0f3ab3d237bc26479eb823444642917245f6e133
script:
  - sonar-scanner
