language: python
python:
  - "3.6"
install:
  - git fetch --unshallow
  - pip install -r requirements_travis.txt

dist:
  trusty

addons:
  sonarcloud:
    organization: szymonmichalski
    token:
      secure: 0f3ab3d237bc26479eb823444642917245f6e133
script:
  - sonar-scanner
  - python -m pytest tests/
